### PR TITLE
added typescript declarations

### PR DESCRIPTION
**Pull request by kaoDev**
Hey,
I used react-native-hockeyapp in a TypeScript project and wanted to contribute my declarations files.

Greetings
Kalle

### CODE REVIEW

**Comment by iamladi** [comment]
@kaoDev Hey, would you be OK if we use instead #72 for the types?

**Comment by iamladi** [comment]
Closed in favor of #72.

**Comment by kaoDev** [comment]
I don't see where #72 adds TypeScript declarations so I think it is not OK or interchangable

**Comment by iamladi** [comment]
@kaoDev Sorry I meant #68. Made copy/paste mistake.

**Comment by kaoDev** [comment]
Ah okay, yes #68 looks better 😀 .

**Comment by iamladi** [comment]
Great. Thanks for the contrib. Very much appreciated. :green_heart:

**Pull request closed without merging**
