### PR TITLE
Fix RN 47 android build

### PR DESCRIPTION
**Pull request by onlydave**
See https://github.com/facebook/react-native/issues/15232

https://github.com/master-atul/react-native-exception-handler/pull/8
https://github.com/mybigday/react-native-s3/pull/53

### CODE REVIEW

**Comment by JonnyPillar** [comment]
Bump on this! Unable to build Android apps with apps running >RN0.47

**Comment by MatthieuPeyrot** [comment]
+1

**Comment by bourgois** [comment]
Dobri dien @martincik 
Could you push that to master? We have to use a fork just because of this old compatibility issue ...
Do you plan to maintain this pakage? Maybe if you need some help, we can find some people interested in maintaining or helping at least...
Thanks

**Comment by iamladi** [comment]
@bourgois Done. Sorry, for such long delay.

**Comment by JonnyPillar** [comment]
@martincik Thanks for sorting that  🎉

**Pull request merged**
