### PR TITLE
Add track event feature

### PR DESCRIPTION
**Pull request by geof90**
This PR:
1. Adds the HockeySDK-4.1.0-beta.1 code to this repository so that we can ship it along with NPM instead of getting users to download it from CocoaPods/MavenCentral, with the advantage that we can ship new beta features included in it.
2. Modifies the README to include setup instructions to link the project to the local HockeySDK
3. Adds the new `trackEvent(eventName)` feature to the API.

Since 1. is gigantic and isn't very valuable to review since it is literally just adding a bunch of files, I extracted change 2. and 3. to a separate diff which you can view here:
https://github.com/geof90/react-native-hockeyapp/compare/add-hockey-sdk-4.1.0.beta.1...geof90:add-track-event-feature?expand=1

@lostintangent @martincik

### CODE REVIEW

**Comment by r0b1n** [comment]
@geof90 thank you for this PR. But I think we need to separate features.
First of all, it will be useful to have `podspec` in project.
Can you create separate PR with `podspec` + `Readme` file please?
And I think we don't need any manual copying to XCode with `pod` installed, so this step should be removed from Readme.

\cc @martincik does it make sense?

**Comment by geof90** [comment]
@r0b1n I had already added the `podspec` in this PR. The `podspec` doesn't make much sense outside of the context of this PR because it requires the HockeyApp binaries added in this PR to work

Also, not all RN users use CocoaPods, there are many examples of plugins that give users a choice whether to use CocoaPods or manual drag+drop to link a plugin.

**Comment by r0b1n** [comment]
@geof90 like for me storing binaries in repo is not perfect idea, but having `podspec` makes module flexible. Why not to add `podspec` which fits current version?

And what is the problem, adding `podspec` don't forces user to use pods. Using it or not is up to user. Even more, without `podspec` we don't have this flexibility.

**Comment by geof90** [comment]
@r0b1n Please read my reply carefully. I said there's no problem adding the podspec, I had already added it if you look in my PR here https://github.com/geof90/react-native-hockeyapp/blob/ef579371ee0878f4c08d10352df4103845d36e11/RNHockeyApp.podspec.

Neither did I say adding the `podspec` forces user to use pods. I'm saying we shouldn't make `podspec` the only way to link the binary. The docs cater to BOTH people who want to use the `podspec` and people who want to manually link.

To your comment about shipping binaries - the binary contains some beta functionality that is not public yet, but we from the Microsoft/HockeyApp team are hoping to expose this functionality via this plugin. Storing binaries is not a novel practice, many plugins do that. The [HockeyApp Cordova plugin](https://github.com/bitstadium/HockeySDK-Cordova/tree/master/src/ios/HockeySDK.embeddedframework/HockeySDK.framework) is a great example.

**Comment by r0b1n** [comment]
@geof90 sorry man, looks like we don't understood each together, in previous comments I was asking about separate PR with your podspec file adopted for current version of the project.

Because looking at author of this project he is not hurry to merge this PR. It is 1 month old, And there is no comments from him in this PR. Maybe he is not sure about merging beta SDK, I don't know.

From my side I just want to have usable podspec module and not to wait while all the things will be merged. I think small useful PR will be merged faster.

Does it make sense?

**Comment by r0b1n** [comment]
@geof90 I mean for now there is no way to use this module by CocoaPods at all. :)

**Comment by iamladi** [comment]
@geof90 Could you extract just the `trackEvent` impl. out of this PR? Thank you.

**Comment by jeveloper** [comment]
Curious if someone can approve this

**Comment by bourgois** [comment]
Indeed it would be great. @martincik could you look at this? It would be great to be able to move to the current version of hockeyapp (4.1.1)... and using pods would make your RN module even easier to use :)

**Comment by iamladi** [comment]
I don't mind working on this although I'm super busy with other projects. The only think I want is to split 2 PRs. PR with the trackEvent code and than the code with Pod stuff. Can we do this?

The reason is I don't have the capacity to review this big PR and I don't want to merge it just because it might break for many people if distributed.

Anyone willing to do the split?

**Comment by jeveloper** [comment]
Hey @geof90 , curious if you can respond :)

**Comment by westcode** [comment]
+1

**Comment by gregberns** [comment]
> 3. Adds the new trackEvent(eventName) feature to the API.

Any one interested in trackEvent(), it was added in PR #49.

**Comment by iamladi** [comment]
Closing in favor of #49.

**Pull request closed without merging**
